# Generated by Django 4.2.9 on 2024-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_chef_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Division', models.CharField(max_length=40)),
                ('rating', models.CharField(max_length=40)),
                ('star', models.CharField(max_length=40)),
                ('H_Rating', models.CharField(max_length=40)),
                ('global_rank', models.CharField(max_length=40)),
                ('country_rank', models.CharField(max_length=40)),
                ('date', models.CharField(editable=False, max_length=20)),
                ('days', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='leet_code_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=40)),
                ('rank', models.CharField(max_length=40)),
                ('prob_sol', models.CharField(max_length=40)),
                ('easy', models.CharField(max_length=40)),
                ('medium', models.CharField(max_length=40)),
                ('hard', models.CharField(max_length=40)),
                ('date', models.CharField(editable=False, max_length=20)),
                ('days', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
